# Generated by Django 4.1.3 on 2023-01-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newprojectapp', '0002_alter_complaint_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='name',
            new_name='user',
        ),
    ]
