# Generated by Django 4.1.3 on 2023-01-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newprojectapp', '0003_rename_name_complaint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='replay',
            field=models.TextField(blank=True, null=True),
        ),
    ]
